sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8
  firefox: 'latest-esr'

cache:
  directories:
  - node_modules

env:
  matrix:
    - EMBER_TRY_SCENARIO=ember-2-8
    - EMBER_TRY_SCENARIO=default
    - EMBER_TRY_SCENARIO=ember-release
  global:
    - CXX=g++-4.8
    - secure: Zflu328okdtasab8EadDgbbVTpSExWZJx8bU/uLR6JLznje252yLyA5ppQbpa6FigCJHSd1GxF2Wr9EPBU0za+TRdM6rrIuLqrcHZc7fWzg6AKOORGznRVMKSwVWyyZqp30XR9Fp9XvzyjJjUaiQ/5RgPq+vTkqO19CRw3V4gXoqgejSjasSgPJ4FQlmmmeg/aiB9cuxu38RTAn2EYQx1Ojas98Cu01Az3sO9Na3xz8/ne4T44DFM4ybX+zalwFjhJj7o4x1FZJD5XZR+BV1EcAU+0KG1c4S7TqidWtcHf06iiIflDNE5rClpPEiuH2I1wI93Df1Q6LmALeNQHhntXWcI4PcablfA4VQFiclSEFmBAd43K7XqZE8FuN5Z/Q0E3/b1OlVupOSu4djaKJ2u94ulaCVbNyeeF32FqaA8n6VltqVTBqqBwfRHNnnLzNe7DPGuwjgyv2tHRh0k0loLPmNOZaMnNqCimX8DmWG4Yocn8oR8X0+7JbLrSziZp9b12h1VUunpVFHaNxevfrrMmjCRI7rHD42AZyYeIM0fi3JzwQbZ+ceYuGtqHHeKf630pwgvyap8cI3DQ6aLA7GFROT/b03N82FzAjCSmL8xmvXIDnaSvXJQKy3j1cjmbuJA2LNGi5Cf+mcNuEyRn1ljMUvE2nsKC2x/UKBnQW5xi4=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-release

before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^1.0.0
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- .travis/maybe-bump-version.sh

after_success:
- .travis/maybe-publish-coverage.sh
- .travis/maybe-publish-gh-pages.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: S+ZT2WdZCkh/rtSIwqAUuGYVmLxLCZ1RFQh5dgOoWZhqxC2haSr4UK1bn6A4uruFjLiLZjJaJ25pAobdtAPSXXKUpIBhEs7spFIUFXik4CxB/yCIqejouMClDt05db4Z+4Y10dNsk2Aku27sP4oqZf2r6p2wQSTU79vPAxEXW2/8VfCsnW1FbQNrCvYm5WwUGLHEXKVj4firuz5EqNHBWEE8Y6p6GCu+0E2QWQ4iZk38YfGHEa/z+Rvcu25Lmb4bbPvpxckkjT9nl/BrV+aVGMgfjHlVcKtDg1m5et2bq2snM5SiCaMuZN7/ijTNQ029+nx+K3dTt5UR6rDm5mr97yq0vH/eXoYv575ph2jqR0qIRSDTCq9JfaH0mzwNaVeZCbuV7oq7vRs/TuCCBbqksaoWOL1/dxOj8/kpypprMiNN92oZe2am2Rrwcx6aWASBBDpJtOYlWa2oHlqP/dl1JQgmUF7KHni6FmfhiQbb6zkMy8RpN4fjpA83BzxaOXzZoUSQSbJPA8P9KR43pRDCNifEzSy+Q/JCX86VFHTh2BN5v4/KJ9iZesaig3WsmtMVfpbSHdSiJFkKqbmp55gDL4oR7g6TkM+GVFrKPA2ToQdZeo6qWaN41FN+S8ENt4hzaoDMrWlQN5igmu1iqNdlyQPlQtXY3kWzkZectsK4ZMk=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: '6.9.1'
    tags: true

notifications:
  slack:
    secure: RUN8mfPn3nozDd8s1hr3owW0ejpgpvURc69idxxzYzBqnNwl0Geeh3j5G8L7mx0PnFNPgqmHA6mbDroVY5LbDGEgYn0EuHIqCY/ebiQ1z6hRoPTSDSXut8MRtEGbIaTx2hfoUKmzlN6kmJic7FtUCrvc5XbAlN/kK3eDCxsiyXyKOjmKouJrB+CnTvb6dyneki7Xc1GvUxKknWH+RsspxJt/EC10AZ+f2UblwT+MkOw1t9XMNtU1ndussTdOqrK13FnHDtPr7PFRYKppItbb7ynWnCUzZOWDNotlrWLUAx/jpV6YSLG0O+c7FoFMF9ZBDLV8gRA/dyYuEPp0rIv3KY52apm395uARXxtpU3Uy2SNXnI2B4HekaCA5kEK2h/McnwPL450my+SfpGZKhcORZWTv/Qtis2cP1x89HhoAz5Zgqpf+aoTzpN9fxzycamcDH/01Kyc+yIZJHUIQ8nYnhlFqcy+/u8F/b2aI7eV9HrZMonCvt0tUOw8T+q5h+MozvvSgfd4u7a1d+U1zUnsWz6VJd2i78yuYJ+QCHNxEyvhyZkttl4glIXITfKFEiYZlzNJ/Th6PfP0M+kfQZ2bEpRO9wj8OgHU13wXb5wRttr+iBTmQiof9v2FsBlAxmzc0XUPJIVkUz1ZG6xAM4/5aAEaHascVwL8EHJOaaooD30=
